# Import the numpy package under the name np


In [2]:
import numpy as np

# Create a null vector of size 10


In [4]:
x = np.zeros((10))
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create a vector with values ranging from 10 to 49 


In [6]:
arr = np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# Find the shape of previous array in question 3


In [8]:
arr.shape

(39,)

# Print the type of the previous array in question 3


In [10]:
arr.dtype

dtype('int32')

# Print the numpy version and the configuration


In [12]:
print(np.__version__)
print(np.show_config())


1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/python/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/python/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/python/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/python/Anaconda3\\Library\\include']
None


# Print the dimension of the array in question 3


In [13]:
np.ndim(arr)

1

# Create a boolean array with all the True values


In [15]:
xyz = np.array(range(1,10), dtype="bool")
xyz

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

# Create a two dimensional array


In [103]:
x= np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
x.ndim

2

# Create a three dimensional array


In [20]:
arr1 = np.arange(1,17)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [21]:
arr1 = arr1.reshape(2,2,4)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [22]:
arr1.ndim

3

# Reverse a vector (first element becomes last)


In [104]:
import numpy as np
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [105]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

# Create a null vector of size 10 but the fifth value which is 1


In [106]:
import numpy as np
arr =np.zeros(10)
print("null values")
arr

null values


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
arr[5] = 1
print("null vector of size 10 but the fifth value is 1")
arr

null vector of size 10 but the fifth value is 1


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# Create a 3x3 identity matrix


In [108]:
import numpy as np
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Convert the data type of the given array from int to float


In [109]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [110]:
arr = np.asfarray(arr)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


# Multiply arr1 with arr2

In [111]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

# Make an array by comparing both the arrays provided above



In [112]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
max = np.maximum(arr1, arr2)
max

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

# Extract all odd numbers from arr with values(0-9)


In [114]:
abc = np.arange(0,9)
abc

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [115]:
abc[1::2]

array([1, 3, 5, 7])

# Replace all odd numbers to -1 from previous array


In [42]:
abc = np.arange(0,9)
abc

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
abc[1::2] = -1
abc

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

# Replace the values of indexes 5,6,7 and 8 to 12



In [45]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5:-1] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

# Create a 2d array with 1 on the border and 0 inside


In [116]:
import numpy as np
x = np.ones((6,6))
print("Original array:")
print(x)


Original array:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [117]:
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


# Replace the value 5 to 12


In [119]:
import numpy as np
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

# Convert all the values of 1st array to 64



In [121]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [122]:
arr3d[0][0][0] = 64
arr3d[0][0][1] = 64
arr3d[0][0][2] = 64
arr3d[0][1][1] = 64
arr3d[0][1][2] = 64
arr3d[0][1][0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d.ndim

3

# Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it


In [123]:
import numpy as np
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
arr[0]

0

# Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it


In [61]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
arr[1,1]

4

# Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows


In [125]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
arr[0:2,2:3]


array([[2],
       [5]])

# Create a 10x10 array with random values and find the minimum and maximum values


In [126]:
import numpy as np
arr = np.random.randint(100 ,size=(10,10))
arr

array([[49, 21, 20,  3, 72, 62, 19, 58, 36, 45],
       [66, 58, 53, 42, 99, 24, 43, 40, 40, 24],
       [49, 23, 30, 26, 37,  0, 76, 47, 67, 14],
       [54, 70, 15, 70, 24, 49, 92, 59, 81, 23],
       [22, 55,  9, 73, 78, 43, 50, 51, 66, 86],
       [39, 87, 64, 22, 37,  6, 73, 71, 26, 81],
       [84, 15, 58, 13, 69, 61, 72, 16, 10, 67],
       [91,  4, 62, 21, 21, 23,  2, 73, 14, 38],
       [13, 58, 50, 65, 98, 81, 15, 75,  5, 12],
       [39, 15, 98, 41, 46, 79, 67,  9, 39, 70]])

In [127]:
print("this is the minimum num in this array")
print(np.min(arr))

print("this is the maximum num in this array")    
print(np.max(arr))

this is the minimum num in this array
0
this is the maximum num in this array
99


# Find the common items between a and b


In [69]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
a , b

(array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]),
 array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8]))

In [70]:
common = np.intersect1d(a,b)
common

array([2, 4])

# Find the positions where elements of a and b match



In [129]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

w = np.where(a == 2)
#x = np.where(a == 3)
y = np.where(b == 2)
#z= np.where(b == 4)
print("THIS IS A")
print(w)
#print("THIS IS A")
#print(x)
print("THIS IS B")
print(y)
#print("THIS IS B")
#print(z)

THIS IS A
(array([1, 3], dtype=int64),)
THIS IS B
(array([1, 3], dtype=int64),)


# Find all the values from array data where the values from array names are not equal to Will


In [130]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[-0.3128187 ,  0.40082605, -0.82862292, -1.16563349],
       [-0.12707937,  0.05453915,  0.24940654, -0.18289031],
       [-0.02960151, -1.40585039,  1.65913454,  1.57333465],
       [ 0.25119856, -1.47544416, -0.65312275, -2.40144778],
       [ 0.41699415,  1.05554308,  0.29423026, -0.44958918],
       [ 0.86832399, -0.46663199,  0.66288192,  0.13713062],
       [-0.40783842, -1.38071532,  0.42015254,  0.32518042]])

In [131]:
data[names != "Will"]

array([[-0.3128187 ,  0.40082605, -0.82862292, -1.16563349],
       [-0.12707937,  0.05453915,  0.24940654, -0.18289031],
       [ 0.25119856, -1.47544416, -0.65312275, -2.40144778],
       [ 0.86832399, -0.46663199,  0.66288192,  0.13713062],
       [-0.40783842, -1.38071532,  0.42015254,  0.32518042]])

# Find all the values from array data where the values from array names are not equal to Will and Joe


In [132]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[-0.14866252, -1.65739903,  1.27253312,  0.69392006],
       [-2.06142388, -0.46145574, -0.3126876 ,  0.12502811],
       [ 1.65091655,  0.40531568, -0.75909713,  0.7823763 ],
       [-0.79014481, -0.49788577,  0.55732474, -0.69610104],
       [ 0.55915316,  0.11205437, -1.41760552,  0.85338106],
       [-1.45421203, -0.96875808, -0.05407681,  0.97364728],
       [ 0.80272151,  0.76622769,  1.42741616,  1.42639595]])

In [133]:
print(data[names != "Will"])
print(data[names != "Joe"])

[[-0.14866252 -1.65739903  1.27253312  0.69392006]
 [-2.06142388 -0.46145574 -0.3126876   0.12502811]
 [-0.79014481 -0.49788577  0.55732474 -0.69610104]
 [-1.45421203 -0.96875808 -0.05407681  0.97364728]
 [ 0.80272151  0.76622769  1.42741616  1.42639595]]
[[-0.14866252 -1.65739903  1.27253312  0.69392006]
 [ 1.65091655  0.40531568 -0.75909713  0.7823763 ]
 [-0.79014481 -0.49788577  0.55732474 -0.69610104]
 [ 0.55915316  0.11205437 -1.41760552  0.85338106]]


# Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.


In [83]:
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)


[[ 8.4080094   9.97717886 10.27389029]
 [ 5.77690353  9.0499353   9.70493927]
 [ 1.36034049  6.60053418  4.02868873]
 [14.27626863 10.62570528  8.5112703 ]
 [ 1.74151655  5.30429362 12.7714565 ]]


# Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.


In [85]:
import numpy as np
arr = np.random.randn(1,16).reshape(2,2,4)
arr

array([[[-0.55268588, -2.45205803, -0.87385406,  1.08958029],
        [-0.10185813, -0.12948372, -1.51716672, -0.53921331]],

       [[ 0.78713702, -1.08770144,  1.01767596, -0.98767615],
        [ 0.30851247,  0.28061886, -1.27784224,  0.42958118]]])

# Swap axes of the array you created in Question 32


In [87]:
arr.T

array([[[-0.55268588,  0.78713702],
        [-0.10185813,  0.30851247]],

       [[-2.45205803, -1.08770144],
        [-0.12948372,  0.28061886]],

       [[-0.87385406,  1.01767596],
        [-1.51716672, -1.27784224]],

       [[ 1.08958029, -0.98767615],
        [-0.53921331,  0.42958118]]])

# Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0


In [89]:
import numpy as np
x = np.arange(10)
x = np.sqrt(x)
np.where(x < 0.5, 0, 0)
x

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

# Find the unique names and sort them out!



In [91]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [92]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

# From array a remove all items present in array b



In [94]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


# Following is the input NumPy array delete column two and insert following new column in its place.


In [136]:
import numpy as np
a = np.array([[34,43,73],[82,22,12],[53,94,66]])

b = np.array([[10,10,10]])

a

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [137]:
c = np.delete(a, 1, axis = 1)
c

array([[34, 73],
       [82, 12],
       [53, 66]])

In [138]:
a[:,1][:] = [10,10,10]
a


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

# Find the dot product of the above two matrix


In [140]:
import numpy.matlib 
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

# Generate a matrix of 20 random values and find its cumulative sum (qno 40)


In [141]:
import numpy as np
import numpy.matlib 

arr = np.random.randint(20)
arr1 = np.cumsum(arr)
arr1

array([1], dtype=int32)